version: "3.8"

services:
  server:
    build: ./restAPI/
    container_name: validation-server
    ports:
      - 3000:3000
    volumes:
      - .\restAPI:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - database

  database:
    build: ./database/
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports: 
      - 5432:5432
    volumes:
      - ./database:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on: 
      - database
    links:
      - "database:postgres"